// <auto-generated />
using LMS.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LMS.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LMS.Models.Entidades.Curso", b =>
                {
                    b.Property<int>("CursoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CursoId"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProfesorId")
                        .HasColumnType("int");

                    b.Property<int>("SedeId")
                        .HasColumnType("int");

                    b.HasKey("CursoId");

                    b.HasIndex("ProfesorId");

                    b.HasIndex("SedeId");

                    b.ToTable("Cursos");
                });

            modelBuilder.Entity("LMS.Models.Entidades.Estudiante", b =>
                {
                    b.Property<string>("Cedula")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SedeId")
                        .HasColumnType("int");

                    b.HasKey("Cedula");

                    b.HasIndex("SedeId");

                    b.ToTable("Estudiantes");
                });

            modelBuilder.Entity("LMS.Models.Entidades.EstudianteCurso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CursoId")
                        .HasColumnType("int");

                    b.Property<string>("EstudianteCedula")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("CursoId");

                    b.HasIndex("EstudianteCedula");

                    b.ToTable("EstudiantesCursos");
                });

            modelBuilder.Entity("LMS.Models.Entidades.EstudianteModulo", b =>
                {
                    b.Property<string>("EstudianteCedula")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("ModuloId")
                        .HasColumnType("int");

                    b.Property<int>("Puntaje")
                        .HasColumnType("int");

                    b.HasKey("EstudianteCedula", "ModuloId");

                    b.HasIndex("ModuloId");

                    b.ToTable("EstudiantesModulos");
                });

            modelBuilder.Entity("LMS.Models.Entidades.Modulo", b =>
                {
                    b.Property<int>("ModuloId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ModuloId"));

                    b.Property<int>("CantidadPreguntas")
                        .HasColumnType("int");

                    b.Property<string>("ContenidoTexto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CursoId")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("NotaMinima")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("Orden")
                        .HasColumnType("int");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VideoPath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ModuloId");

                    b.HasIndex("CursoId");

                    b.ToTable("Modulos");
                });

            modelBuilder.Entity("LMS.Models.Entidades.Pregunta", b =>
                {
                    b.Property<int>("PreguntaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PreguntaId"));

                    b.Property<string>("Enunciado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ModuloId")
                        .HasColumnType("int");

                    b.Property<string>("OpcionA")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OpcionB")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OpcionC")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OpcionD")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RespuestaCorrecta")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PreguntaId");

                    b.HasIndex("ModuloId");

                    b.ToTable("Preguntas");
                });

            modelBuilder.Entity("LMS.Models.Entidades.Profesor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Passwd")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SedeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SedeId");

                    b.ToTable("Profesores");
                });

            modelBuilder.Entity("LMS.Models.Entidades.ResultadoModulo", b =>
                {
                    b.Property<int>("ResultadoModuloId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ResultadoModuloId"));

                    b.Property<bool>("Aprobado")
                        .HasColumnType("bit");

                    b.Property<string>("EstudianteCedula")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("ModuloId")
                        .HasColumnType("int");

                    b.Property<decimal>("NotaObtenida")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("ResultadoModuloId");

                    b.HasIndex("EstudianteCedula");

                    b.HasIndex("ModuloId");

                    b.ToTable("ResultadosModulos");
                });

            modelBuilder.Entity("LMS.Models.Entidades.Sede", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Sedes");
                });

            modelBuilder.Entity("LMS.Models.Entidades.Curso", b =>
                {
                    b.HasOne("LMS.Models.Entidades.Profesor", "Profesor")
                        .WithMany("Cursos")
                        .HasForeignKey("ProfesorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LMS.Models.Entidades.Sede", "Sede")
                        .WithMany("Cursos")
                        .HasForeignKey("SedeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Profesor");

                    b.Navigation("Sede");
                });

            modelBuilder.Entity("LMS.Models.Entidades.Estudiante", b =>
                {
                    b.HasOne("LMS.Models.Entidades.Sede", "Sede")
                        .WithMany("Estudiantes")
                        .HasForeignKey("SedeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Sede");
                });

            modelBuilder.Entity("LMS.Models.Entidades.EstudianteCurso", b =>
                {
                    b.HasOne("LMS.Models.Entidades.Curso", "Curso")
                        .WithMany("EstudiantesCursos")
                        .HasForeignKey("CursoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LMS.Models.Entidades.Estudiante", "Estudiante")
                        .WithMany("EstudiantesCursos")
                        .HasForeignKey("EstudianteCedula")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Curso");

                    b.Navigation("Estudiante");
                });

            modelBuilder.Entity("LMS.Models.Entidades.EstudianteModulo", b =>
                {
                    b.HasOne("LMS.Models.Entidades.Estudiante", null)
                        .WithMany()
                        .HasForeignKey("EstudianteCedula")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LMS.Models.Entidades.Modulo", null)
                        .WithMany()
                        .HasForeignKey("ModuloId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LMS.Models.Entidades.Modulo", b =>
                {
                    b.HasOne("LMS.Models.Entidades.Curso", "Curso")
                        .WithMany("Modulos")
                        .HasForeignKey("CursoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Curso");
                });

            modelBuilder.Entity("LMS.Models.Entidades.Pregunta", b =>
                {
                    b.HasOne("LMS.Models.Entidades.Modulo", "Modulo")
                        .WithMany("Preguntas")
                        .HasForeignKey("ModuloId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Modulo");
                });

            modelBuilder.Entity("LMS.Models.Entidades.Profesor", b =>
                {
                    b.HasOne("LMS.Models.Entidades.Sede", "Sede")
                        .WithMany("Profesores")
                        .HasForeignKey("SedeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Sede");
                });

            modelBuilder.Entity("LMS.Models.Entidades.ResultadoModulo", b =>
                {
                    b.HasOne("LMS.Models.Entidades.Estudiante", null)
                        .WithMany()
                        .HasForeignKey("EstudianteCedula")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LMS.Models.Entidades.Modulo", null)
                        .WithMany()
                        .HasForeignKey("ModuloId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LMS.Models.Entidades.Curso", b =>
                {
                    b.Navigation("EstudiantesCursos");

                    b.Navigation("Modulos");
                });

            modelBuilder.Entity("LMS.Models.Entidades.Estudiante", b =>
                {
                    b.Navigation("EstudiantesCursos");
                });

            modelBuilder.Entity("LMS.Models.Entidades.Modulo", b =>
                {
                    b.Navigation("Preguntas");
                });

            modelBuilder.Entity("LMS.Models.Entidades.Profesor", b =>
                {
                    b.Navigation("Cursos");
                });

            modelBuilder.Entity("LMS.Models.Entidades.Sede", b =>
                {
                    b.Navigation("Cursos");

                    b.Navigation("Estudiantes");

                    b.Navigation("Profesores");
                });
#pragma warning restore 612, 618
        }
    }
}
